### ISSUE TITLE
Content of Dockerfile appears empty

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-docker#140]
The content of the Dockerfile that is supposed to be created isn't displayed.

<img width="642" alt="Screen Shot 2021-10-13 at 12 07 34 AM" src="https://user-images.githubusercontent.com/4803104/137065666-6df03cd5-a182-476c-a10b-94498d1c63ce.png">

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by yeekangc** [comment]
- The code block should show full path to the Dockerfile
- In single pane or mobile view, clicking on the code block to show the file content doesn't work consistently or didn't work after first use

**Comment by gkwan-ibm** [comment]
opened https://github.com/OpenLiberty/openliberty.io/issues/2307 for
> In single pane or mobile view, clicking on the code block to show the file content doesn't work consistently or didn't work after first use

**Comment by gkwan-ibm** [comment]
close
- https://github.com/OpenLiberty/openliberty.io/issues/2307 was fixed
