### ISSUE TITLE
Update the guide to point to official open-liberty repo 

### ISSUE THREAD

**Issue by arturdzm** [OpenLiberty/guide-docker#15]
Guide is using openliberty/open-liberty 

We now have official repository,  guide is still using public repo which is out of date:
https://hub.docker.com/_/open-liberty/ 

Need to change Dockerfile FROM directive

**Comment by Kubik42** [comment]
fixed in 298db18c426b55467c91a5ecce4ab894f1546374

**Comment by arturdzm** [comment]
Looks good now, thanks
