### ISSUE TITLE
Python example seems odd in Java guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-docker#20]
I was just reading the Docker guide and the intro bit uses having multiple versions of Python as an example of why you might want to use containers. At the point where it says "You can also run multiple containers on a single machine in isolation from one another so that two containers that have different versions of Python do not interfere with each other." it makes me wonder why I'm going to be doing Python stuff in this guide. I think the Python example is fine for a generic explanation of why Docker/containers are useful but it doesn't seem very relevant to a guide on writing Java apps for a Java app server.

More importantly, it doesn't explain why someone working with Open Liberty or Java EE/MP would want to use a Docker environment for development. Which would be more important to someone pondering whether to continue reading/doing the Docker guide.

**Comment by Kubik42** [comment]
Good point. The Python example was just a general case I wanted to present, it has nothing to do with the guide. I suppose I can do the same analogy but with java. As for being Open Liberty specific, I though we wanted to not focus on open liberty and microprofile? Hence, the whole rework concerning the titles of the guides. My understanding is that users would want to learn about Docker and we teach them, but it just so happens that we use Open Liberty for it. This makes users more inclined to chose OL for future docker work since they are already sort of accustomed to it.

**Comment by lauracowen** [comment]
Yeah, JavaEE/MP is the relevant bit as you say. Java EE/MP spec versions might work - eg an old version of JAX-RS or something? (check that that's a plausible/common problem though).

**Comment by Kubik42** [comment]
See #25

**Comment by ebullient** [comment]
This has been sitting, but.. "My understanding is that users would want to learn about Docker and we teach them, but it just so happens that we use Open Liberty for it." -- I found the following really confusing: 
```
# Start with OL runtime.
FROM open-liberty

# Symlink servers directory for easier mounts.
RUN ln -s /opt/ol/wlp/usr/servers /servers

# Run the server script and start the defaultServer by default.
ENTRYPOINT ["/opt/ol/wlp/bin/server", "run"]
CMD ["defaultServer"]
```

As far as this guide goes, the use of symlinks or volume mounts hasn't been mentioned at all, so the relevance of the symlink as a thing to do is dubious.

The ENTRYPOINT and CMD are a little off what the base liberty image does -- but it's pretty thin on what that means, etc. 

I would simplify this to some of the main cases we have here: https://github.com/OpenLiberty/ci.docker/tree/master/openliberty/microProfile2/java8/ibmjava

Documentation matching w/ recommended examples (and enough context) is wonderful.

(the read-only stuff is good, but off-topic for docker guide, unless you want a whole subsection of the guide to talk about volume mounts .. but do it all together)

**Comment by gkwan-ibm** [comment]
#74 will have a different development experience to develop application with docker container

**Comment by gkwan-ibm** [comment]
close
- the [guide](https://openliberty.io/guides/docker.html) is using devc mode  to develop application with docker container
