### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-docker#31]
- [x] `<execution />` element tag in `Building your application` has the slash in the wrong place

- [x] PropertiesResource should be one word in `Testing the container` and file should be removed 

- [x] ```Change the endpoint of your application from /properties to /properties-new by replacing the PropertiesResource.java class and changing the @Path annotation to "properties-new".*```
should be 
```Change the endpoint of your application from /properties to /properties-new by changing the @Path annotation to "properties-new".*```

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-docker/commit/cb7af331c83e19bde4eb05928e02503776220e6d

**Comment by justineechen** [comment]
- [ ] Parent POM 
- [ ] Format files 
- [ ] Failsafe Plugin
- [ ] .yaml quiet flag

**Comment by justineechen** [comment]
- [ ] "Now that your image is built, execute the Docker run command **with the absolute path to this guide**, from the command line to run it:"
```
docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/servers ol-runtime
```

**Comment by Rachelwrq** [comment]
#### Build your application:

- [ ] ….”REST application to the `defaultServer` server.pom.xml” is unclear
Execution element hotspot: should it include the comment? And also it appears that the hotspot covered everything underneath

#### Creating the Dockerfile
- [ ] Switch the order between CMD and ENTRYPOINT?

#### Testing the container
- [ ] Hotspot for action arrow: exclude the package and import above

**Comment by justineechen** [comment]
- [x] "Learn how to containerize a microservice with Docker for iterative development." -> with the period

**Comment by justineechen** [comment]
- [x] The implementation of the REST application can be found in the
`start/src` directory.

**Comment by Rachelwrq** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present

**In the README.adoc:**
- [ ] Tags in the front matter are correct
     - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
     - [ ] start directory
     - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by andrewdes** [comment]
> Your pom.xml file is already configured to add your REST application to the defaultServer.

> But you can tweak this configuration or add your own for another server by updating the <execution/> element.

- [ ] Above should be combined to be one paragraph
- [ ]  `<execution/>` hotspot showing wrong lines
- [ ] "Create the `Docker` file." -> "Create the Dockerfile."
- [ ] “In this case, you’re using the openliberty/open-liberty:javaee7 image as your parent image, which comes with the latest Open Liberty runtime.” Should this be Java EE 8?
- [ ] .yaml file needs `-q` flag

**Comment by Rachelwrq** [comment]
- [ ] Add more hotspots for commands **Creating the Dockerfile** Section
- [ ] In **Testing the container** section: `mvn package` command is not in the right format

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
