### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-docker#34]
**Building your application**
- [ ] Does this guide need the `clean` goal? I thought we were removing `clean` from the guides

**Creating the Dockerfile** 
- [x] This guide does not tell users to "Navigate to the start directory" before giving instructions to modify/create files. 
- [x] Path to Dockerfile includes "start" directory: start/Dockerfile (**only applicable if point above is taken into consideration**)

**Optional: Writing a .dockerignore file**
- [x] Feel free to add anything else that you want to exclude -> No period at the end of the sentence
- [ ] Should the .dockerignore file be hotspotted and displayed on the right pane?

**Containerize your application**
- [x] "Now that your image is built, execute the Docker run command with the absolute path to this guide, from the command line to run it:" -> "from the command line to run it:" needs to be reworded
- [ ] "This flag gives the container a name." -> The description for the `--name` flag could be improved. The flag allows you to specify/give the container a name, I feel like the current description makes it sounds as though the --name flag automatically gives the container a name
- [x] For example, if your servers directory also contains a server called testServer, then it can be started as shown in the following example: -> Should the command listed after be copyable? Since it is copyable it could be misleading, because we don't actually want users to run this command do we?

**Testing the container**
- [x] The path for the PropertiesResource class has the `start` directory in it (start/src/main/java/io/openliberty/guides/rest/PropertiesResource.java), if we want to be consistent with other guides we should tell users to navigate to the start directory at the beginning and omit it from paths

**Comment by justineechen** [comment]
- I don't think it's necessary to show the .dockerignore file 

- I think "This flag gives the container a name" is fine because it follows the wording of the other descriptions in this table, which are pretty concise. I think changing it to 'allows you to give/specify' doesn't change the meaning of that sentence.

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/guide-docker/commit/5933e33b6d330353723760ee57c5bdd6506760ec

**Comment by andrewdes** [comment]
@justineechen I don't think that "This flag gives the container a name" is fine. Yes it is concise, but it is not accurate. When I mentioned that the flag allows you to specify a name for the container, I wasn't suggesting that exact wording, I was just proving my point that the current explanation should be improved. Perhaps something along the lines of "Specifies a name for the container." like in the getting-started guide.

In other guides, when a file is being talked about it is hotspotted and displayed in the right pane. Why should the .dockerignore be treated differently?

- [ ] "Navigate to your start directory." -> Not consistent with phrasing from other guides. Other guides also have this sentence as the first sentence of the section.

**Comment by justineechen** [comment]
- Okay, although ID already reviewed those words when the guide was published, I will change it because the wording makes the guide more accurate. 

- I've added the `.dockerignore`, I thought maybe it would be unproductive if the editor didn't show hidden files but I think most do or they can use vim
