### ISSUE TITLE
Docker Guide has been broken by latest OL docker image

### ISSUE THREAD

**Issue by websterc87** [OpenLiberty/guide-docker#38]
The dockerfile contained in this guide no longer works.  It now fails to create a symlink for /servers due to the OL image changing to use a non root user (https://github.com/OpenLiberty/ci.docker/commit/0d10f95e06d7f00752bd60f76964f64e59de4af5)

**Comment by evelinec** [comment]
We tested it last week and there wasn't any problem with this command.. Just tried now, it gives the following error: 

docker build -t ol-runtime .
Sending build context to Docker daemon  153.1MB
Step 1/4 : FROM open-liberty
 ---> 19806cd7eebb
Step 2/4 : RUN ln -s /opt/ol/wlp/usr/servers /servers
 ---> Running in 69f5e98414fb
ln: failed to create symbolic link '/servers': Permission denied
The command '/bin/sh -c ln -s /opt/ol/wlp/usr/servers /servers' returned a non-zero code: 1

**Comment by yeekangc** [comment]
Thank you for filing the issue, @websterc87.  We are addressing.

**Comment by gkwan-ibm** [comment]
- GK will merge the PR
- will do test on qa
