### ISSUE TITLE
Hardcoded path in automation test

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-docker#41]
The current automation test hardcodes the path `/home/travis/build/OpenLiberty` in the test command. This may be a problem?

`docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v /home/travis/build/OpenLiberty/guide-docker/finish/target/liberty/wlp/usr/servers:/servers ol-runtime`

**Comment by gkwan-ibm** [comment]
close
- no hard-code now, maybe already fixed
