### ISSUE TITLE
Cannot run docker container on MacOS

### ISSUE THREAD

**Issue by varminas** [OpenLiberty/guide-docker#48]
In the finished directory I executed following commands:
`mvn clean install`
`docker build -t ol-runtime . `
`docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v /MY_ABSOLUTE_PATH_TO_FINISHED_DIR/target/liberty/wlp/usr/servers:/servers ol-runtime`

However, container failed with the following error (can see by executing `docker logs rest-app`:
```
JVMSHRC155E Error copying username into cache name
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified
CWWKE0005E: The runtime environment could not be launched.
CWWKE0044E: There is no write permission for server directory /opt/ol/wlp/output/defaultServer
```

MacOS Mojave: v10.14.4

**Comment by gkwan-ibm** [comment]
hi @varminas, we cannot reproduce your problem. By the errors, it should be related to user and directory permission.  To help us to diagnose it, you would provide us the following information:
1. May we assume that you did not change the Dockerfile and/or other file?
1. May we assume that you had no problem to build the image by `docker build -t ol-runtime .`?
1. Would you capture and send us the output the following commands:
    - `mvn -version`
    - `ls -la /MY_ABSOLUTE_PATH_TO_FINISHED_DIR/target`
    - `ls -la /MY_ABSOLUTE_PATH_TO_FINISHED_DIR/target/liberty/wlp/usr/servers/`
1. Can the container still run after `docker run ...`? If it can, would you check the access right of the output directory and send us the output by the following command?
    - `docker exec -it rest-app ls -la /opt/ol/wlp/output`


 
Thanks!

**Comment by varminas** [comment]
Hello @gkwan-ibm.
1. Original code (from the folder "**finish**" has not been changed.
2. There is no problem to build the image with this command `docker build -t ol-runtime .`:
```
Sending build context to Docker daemon  150.8MB
Step 1/6 : FROM open-liberty
 ---> ed1ca62c4bd5
Step 2/6 : USER root
 ---> Running in 437ac2327f5c
Removing intermediate container 437ac2327f5c
 ---> 172c26fabae9
Step 3/6 : RUN ln -s /opt/ol/wlp/usr/servers /servers
 ---> Running in 381e0fe54aca
Removing intermediate container 381e0fe54aca
 ---> a5dead350e64
Step 4/6 : USER 1001
 ---> Running in 6b69bbfa7006
Removing intermediate container 6b69bbfa7006
 ---> ea11c9df802b
Step 5/6 : ENTRYPOINT ["/opt/ol/wlp/bin/server", "run"]
 ---> Running in 72179a29ee55
Removing intermediate container 72179a29ee55
 ---> 8a846a40d4eb
Step 6/6 : CMD ["defaultServer"]
 ---> Running in f7617378ad51
Removing intermediate container f7617378ad51
 ---> 40888a780978
Successfully built 40888a780978
Successfully tagged ol-runtime:latest
```
3.
`mvn -version`

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```
`ls -la target`

```
total 24
drwxr-xr-x  13 myuser  staff   416 May 25 23:53 .
drwxr-xr-x   9 myuser  staff   288 May 25 23:53 ..
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 classes
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 generated-sources
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 generated-test-sources
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 liberty
-rw-r--r--   1 myuser  staff  2027 May 25 23:53 liberty-plugin-config.xml
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 maven-archiver
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 maven-status
drwxr-xr-x   5 myuser  staff   160 May 25 23:53 rest-1.0-SNAPSHOT
-rw-r--r--   1 myuser  staff  6478 May 25 23:53 rest-1.0-SNAPSHOT.war
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 test-classes
drwxr-xr-x   3 myuser  staff    96 May 25 23:53 test-reports
```
` ls -la target/liberty/wlp/usr/servers`

```
total 0
drwxr-x---  5 myuser  staff  160 May 25 23:53 .
drwxr-x---  3 myuser  staff   96 May 25 23:53 ..
drwxr-x---  2 myuser  staff   64 May 25 23:53 .logs
drwxr-x---  2 myuser  staff   64 May 25 23:53 .pid
drwxr-x---  9 myuser  staff  288 May 25 23:53 defaultServer
```
4. 
`docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v MY_ABSOLUTE_PATH_TO_FINISHED_DIR/target/liberty/wlp/usr/servers:/servers ol-runtime`:

after this command container is created, but there is no active container, it exited with the error code:
`docker ps -a`

```
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS                           PORTS               NAMES
604e9d2c117f        ol-runtime            "/opt/ol/wlp/bin/ser…"   About a minute ago   Exited (24) About a minute ago                       rest-app
```
The logs of the container
`docker logs 604`
```
JVMSHRC155E Error copying username into cache name
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified
CWWKE0005E: The runtime environment could not be launched.
CWWKE0044E: There is no write permission for server directory /opt/ol/wlp/output/defaultServer
```

**Comment by gkwan-ibm** [comment]
hi @varminas , thanks for your information. Would you mind to tell us which version of docker you are using?
- `docker version`

**Comment by varminas** [comment]
Hi @gkwan-ibm,
```
docker --version
Docker version 18.09.2, build 6247962
```

**Comment by varminas** [comment]
I think the problem could be open-liberty image version. Despite image is "latest", probably it's not the latest one, i.e. not 19.0.0.4

**Comment by andrewdes** [comment]
Can you run `docker pull open-liberty`. Does this pull a newer image?

**Comment by gkwan-ibm** [comment]
or run open-liberty image directly instead of ol-runtime, then run `docker exec -it rest-app cat /logs/messages.log`,  it should show the something like
```
********************************************************************************
product = Open Liberty 19.0.0.4 (wlp-1.0.27.cl190420190419-0642)
wlp.install.dir = /opt/ol/wlp/
server.output.dir = /opt/ol/wlp/output/defaultServer/
java.home = /opt/ibm/java/jre
java.version = 1.8.0_211
java.runtime = Java(TM) SE Runtime Environment (8.0.5.36 - pxa6480sr5fp36-20190510_01(SR5 FP36))
os = Linux (4.9.125-linuxkit; amd64) (en_US)
process = 1@172.17.0.2
********************************************************************************
```

**Comment by varminas** [comment]
After pulling the latest version it can start as expected. This was really version problem. It was couple months old version. So, this issue is no more actual. Thanks for the support.
