### ISSUE TITLE
dockerfile when ready to build app image

### ISSUE THREAD

**Issue by Charek** [OpenLiberty/guide-docker#52]
This guide shows how to setup development with a continuously running open liberty docker container. Two questions
1) Why would we want to create our own custom docker image just to run open liberty? Eg. `docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/servers ol-runtime  `
When it seems that we could reference the official image
`docker run -d --name rest-app -p 9080:9080 -p 9443:9443 -v <absolute path to guide>/start/target/liberty/wlp/usr/servers:/liberty/usr/servers open-liberty` 

2) What should the dockerfile look like when we are ready to create an image including the application? I read about copying the .war and server.xml to the /config dir. Or is it sufficient to  copy the target servers directory as the docker mount argument. What are best practices?

**Comment by gkwan-ibm** [comment]
Thanks @Charek,

1. Good observation, we will look into your suggestion.
2. To build a docker image including application, you may visit the [Containerizing microservices](https://openliberty.io/guides/containerize.html) guide.

**Comment by arthurdm** [comment]
@Charek - I have outlined some improvements to that guide in https://github.com/OpenLiberty/guide-docker/issues/69

**Comment by gkwan-ibm** [comment]
close
- the guide was updated to use LMP `liberty:devc` mode for development
