### ISSUE TITLE
"Using Docker containers to develop microservices" page has broken link

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/guide-docker#54]
@blekione commented on [Tue Sep 24 2019](https://github.com/OpenLiberty/openliberty.io/issues/1398)

https://openliberty.io/guides/docker.html#building-your-application section has broken link in the paragraph:
"Learn more about this goal on the official `Maven Liberty plug-in repository`. "

It shows 404 error.

Same goes for https://github.com/openliberty/guide-docker#building-your-application

**Comment by yeekangc** [comment]
The repos were moved from WASdev to under OpenLiberty.  Need to update the links.

**Comment by yeekangc** [comment]
@gkwan-ibm, looks like we need to update the guide for LMP 3.0 and dev mode too?
