### ISSUE TITLE
Update guide to have more descriptive title

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/guide-docker#66]
In Slack (and probably other chat platforms), this guide is using the default title `Open Liberty`.  Let's add more details to the title that is specific to this guide.  See picture below from Slack that shows the difference with this `docker` guide relative to the other guides' titles.

![image](https://user-images.githubusercontent.com/31117513/68874264-88678b80-06c6-11ea-860a-5fa7bcd31d4a.png)

**Comment by MaiHameed** [comment]
[Fixed](https://github.com/OpenLiberty/guide-docker/pull/68) Closing.
