### ISSUE TITLE
Improvements to Docker guide

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/guide-docker#69]
I suggest we update the Docker guide to demonstrate the best practices as outlined in https://github.com/OpenLiberty/ci.docker#building-an-application-image

It should:

- start from the official image (I would recommend the UBI image, such as `openliberty/open-liberty:full-java8-openj9-ubi`)
- copy the server.xml and application (using `chown`)
- call configure.sh (this will do things like start/stop the server for improved performance)
- avoid using volumes, unless it's for things like keystore / cert which are usually bound in a k8s env. 

We don't need to use the `ENTRYPOINT` or `CMD` instructions because that's already present in the official OL images.

**Comment by yeekangc** [comment]
This guide isn't for creating an image but for doing iterative development with the runtime running in a container.

Instead, the Containerize guide is the guide for creating an image.

Thanks for the feedback, Arthur.  We will consider and update where appropriate and necessary.  Will reach out to further discuss if necessary too.

**Comment by yeekangc** [comment]
@gkwan-ibm, are we ready to update the guide to follow the practices outlined for our images?

e.g., use features.sh and configure.sh to setup what is needed?

**Comment by gkwan-ibm** [comment]
The guide followed the practices before. The practices were changed in sometime to use `kernel-slim` and `features.sh`. That changes cause MST and devc not work properly with timeout issue. That’s why the guides do not follow the practices yet. Need to investigate the real impact, the possibility to extend the timeout and whether the timeout is acceptable.

**Comment by gkwan-ibm** [comment]
The https://openliberty.io/guides/containerize.html#creating-your-dockerfiles explains to use full vs kernel-slim images.

**Comment by gkwan-ibm** [comment]
close
- [explained why use full image](https://github.com/OpenLiberty/guide-docker/issues/69#issuecomment-1303658258)
- The copy commands are using `--chown`
- not use `configure.sh` because MST and devc not work properly with timeout issue.
- does not use volume, E`NTRYPOINT` and `CMD`
