### ISSUE TITLE
Update guide to use devc mode

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-docker#74]
refactor the guide
- [x] use new LMP for devmode with container
- [x] use ideal Dockefile
- [x] use ideal pom 
- [x] use latest mp
- [x] use jakartaee
- [x] use dev mode 
- [x] #72
- [x] remove jdk9+ dependencies https://github.com/OpenLiberty/guides-common/issues/459 (was able to remove all except for one)

- [x] Update tests to JUnit 5
- [x] Rewrite guide for devmode with container

**Comment by gkwan-ibm** [comment]
- addressing SME feedback

**Comment by gkwan-ibm** [comment]
- addressed SME feedback
- next user review

**Comment by gkwan-ibm** [comment]
- addressing feedback from playback demo

**Comment by gkwan-ibm** [comment]
- addressed feedback from playback demo
- need to describe the objective of this guide (vs the containerize guide)

**Comment by gkwan-ibm** [comment]
pending the LMP to support dev mode with container

**Comment by yeekangc** [comment]
Support is GA in 3.3 release of Liberty Maven plugin.  Let us proceed to wrap this up.  Thank you!

**Comment by gkwan-ibm** [comment]
ID review in progress

**Comment by gkwan-ibm** [comment]
ready to publish

**Comment by yeekangc** [comment]
@jamiecoleman92

**Comment by yeekangc** [comment]
LGTM.  Thank you, @griffinhadfield @gkwan-ibm.  Let us proceed to publish the updates.

**Comment by gkwan-ibm** [comment]
close
- added a new section for devc at https://openliberty.io/guides/docker.html#launching-open-liberty-in-dev-mode
